- id: commit-msg-guardian
  name: commit-msg-guardian
  description: Validates commit messages against specified rules (language, format, etc.)
  entry: commit-msg-guardian
  language: golang
  pass_filenames: true
  stages:
    - commit-msg
  args:
    - --type-rules=allowLatin
    - --scope-rules=allowScope
    - --description-rules=noCyrillic
